spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #配置当前要使用的数据源的操作类型那个
    driver-class-name: org.gjt.mm.mysql.Driver       #配置MySQL的驱动程序类
    url: jdbc:mysql://10.130.0.73:3306/paycenter?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=Hongkong&useSSL=false
    username: jwell56
    password: qbj@Jwabc,.56
    filters: stat,wall,log4j     #druid监控配置
    dbcp2:
      min-idle: 5         #数据库连接池的最小维持连接数
      initial-size: 5     #初始化提供的连接数
      max-total: 5          #最大的连接数
      max-wait-millis: 200        #等待连接获取的最大超时时间


  　　
