server:
  port: 3333
  servlet:
    context-path: /pay

urls:
  permit:
    - /**/swagger-resources/**
    - /swagger-ui.html
    - /**/v2/api-docs
    - /swagger/api-docs
    - /webjars/**

spring:
  application:
    name: yp-pay-service
  #profile:
    #active: local
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #com.alibaba.druid.pool.DruidDataSource org.apache.commons.dbcp.BasicDataSource 配置当前要使用的数据源的操作类型那个
    driver-class-name: com.mysql.cj.jdbc.Driver       #配置MySQL的驱动程序类
    url: jdbc:mysql://10.130.0.73:3306/paycenter?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=Hongkong&useSSL=false
    username: jwell56
    password: qbj@Jwabc,.56
    filters: stat,wall,log4j     #druid监控配置 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    dbcp2:
      min-idle: 5         #数据库连接池的最小维持连接数
      initial-size: 5     #初始化提供的连接数
      max-total: 5          #最大的连接数
      max-wait-millis: 200        #等待连接获取的最大超时时间

mybatis:
  config-location: classpath:mybatis-config.xml
  executorType: SIMPLE
  mapper-locations: classpath:mapper/*Mapper.xml

app:
  id: yp-pay-service
