server:
  port: 3333
  servlet:
    context-path: /pay

app:
  id: yp-pay-service

urls:
  permit:
    - /**/swagger-resources/**
    - /swagger-ui.html
    - /**/v2/api-docs
    - /swagger/api-docs
    - /webjars/**

spring:
  application:
    name: yp-pay-service
  profiles:
    active: local
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848 #配置中心地址
        file-extension: yaml #dataId = application.name + file-extension
        namespace: 2c384c36-b3b2-41ed-875f-70a1dbc4fedc #命名空间
        group: DEFAULT_GROUP

mybatis:
  config-location: classpath:mybatis-config.xml
  executorType: SIMPLE
  mapper-locations: classpath:mapper/*Mapper.xml

